ProgComp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include('prog_auth.urls')),
]

prog_auth/urls.py
from django.urls import path
from prog_auth import views

app_name = 'prog_auth'

urlpatterns = [
    path('login/', views.Login, name='login'),
    path('home/', views.Home, name='home'),
    path('logout/', views.Logout, name='logout'),
]

prog_auth/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class User(User):
    grupo = models.CharField(max_length=50)
    materia = models.CharField(max_length=50)
    
    def __str__(self):
        return self.username
    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

prog_auth/views.py
from turtle import up
from django.shortcuts import redirect, render
from urllib import request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .models import User

# Create your views here.
def Login(request):
    if 'login' in request.POST:
        username = request.POST['log_username']
        password = request.POST['log_password']
        try:
            a = login(request, authenticate(username=username, password=password))
            print(a)
            return redirect('prog_auth:home')
        except:
            messages.error(request, 'Usuario o contraseña incorrectos')
    elif 'register' in request.POST:
        try:
            user = User()
            user.username = request.POST['reg_username']
            user.email = request.POST['reg_email']
            user.first_name = request.POST['reg_first_name']
            user.last_name = request.POST['reg_last_name']
            user.set_password(request.POST['reg_password'])
            user.save()
            print('Usuario registrado')
            messages.success(request, 'Usuario registrado')
        except:
            messages.error(request, 'Error al registrar usuario')
    return render(request, 'login.html')

def Home(request):
    users = User.objects.all()
    if "delete" in request.POST:
        user = User.objects.get(username=request.POST['delete'])
        user.delete()
        print("Usuario eliminado")
    elif "update" in request.POST:
        up_user = User.objects.get(username=request.user.username)
        up_user.first_name=request.POST['new_first_name']
        up_user.last_name=request.POST['new_last_name']
        up_user.email=request.POST['new_email']
        up_user.save()

    return render(request, 'home.html', {'users': users})

def Logout(request):
    logout(request)
    return redirect('prog_auth:login')

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <style>
        table,
        th,
        td {
            border: 1px solid black;
        }
    </style>
</head>

<body>
    <form action="" method="post">
        <h1>Home</h1>
        <br>
        <p>Nombre de usuario: {{ user.username }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Nombres: {{ user.first_name }}</p>
        <p>Apellidos: {{ user.last_name }}</p>
        <p>Contraseña: {{ user.password }}</p>
        <h3>Actualizar</h3>
        <input type="text" name="new_first_name" placeholder="Nombres">
        <input type="text" name="new_last_name" placeholder="Apellidos">
        <input type="text" name="new_email" placeholder="Email">
        <button type="submit" name="update">Actualizar</button>
        <a href="{% url 'prog_auth:logout' %}">Logout</a>
        <br><br>

        {% csrf_token %}
        <table style="width:100%">
            <thead>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Nombre de usuario</th>
                <th>Contraseña</th>
                <th>Accion</th>
            </thead>
            {% for user in users %}
            <tr>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
                <td><button value="{{ user.username }}" type="submit" name="delete">Eliminar</button></td>
            </tr>
            {% endfor %}

        </table>
    </form>
</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesion</title>
    <link href='{% static "login.css" %}' rel="stylesheet" />
</head>

<body>
        <section>
            {% if message %}
            <div class="alert alert-danger">
                <h2>{{ message }}</h2>
            </div>
            {% endif %}
            <div class="container">
                <div class="user signinBx">
                    <div class="imgBx"><img
                            src="https://raw.githubusercontent.com/WoojinFive/CSS_Playground/master/Responsive%20Login%20and%20Registration%20Form/img1.jpg"
                            alt="" /></div>
                    <div class="formBx">
                        <form action="" method="post">
                            {% csrf_token %}
                            <h2>Iniciar Sesion</h2>
                            <input type="text" name="log_username" placeholder="Nombre usuario" />
                            <input type="password" name="log_password" placeholder="Contraseña" />
                            <input type="submit" value="Ingresar" name="login" />
                            <p class="signup">
                                No tienes una cuenta?
                                <a href="#" onclick="toggleForm();">Registrar.</a>
                            </p>
                        </form>
                    </div>
                </div>
                <div class="user signupBx">
                    <div class="formBx">
                        <form action="" method="post">
                            {% csrf_token %}
                            <h2>Crear cuenta</h2>
                            <input type="text" name="reg_username" placeholder="Nombre usuario" />
                            <input type="email" name="reg_email" placeholder="Email" />
                            <input type="text" name="reg_first_name" placeholder="Nombres" />
                            <input type="text" name="reg_last_name" placeholder="Apellidos" />
                            <input type="password" name="reg_password" placeholder="Contraseña" />
                            <input type="password" name="reg_c_password" placeholder="Confirmar contraseña" />
                            <input type="submit" value="Registrar" name='register' />
                            <p class="signup">
                                Ya tienes una cuenta?
                                <a href="#" onclick="toggleForm();">Iniciar sesion.</a>
                            </p>
                        </form>
                    </div>
                    <div class="imgBx"><img
                            src="https://raw.githubusercontent.com/WoojinFive/CSS_Playground/master/Responsive%20Login%20and%20Registration%20Form/img2.jpg"
                            alt="" /></div>
                </div>
            </div>
        </section>
    <script src='{% static "login.js" %}'></script>
</body>

</html>